#!/usr/bin/env python3
from subprocess import PIPE, run
def out(command):
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)
    return (result.stdout).strip()

branch_name = out('git branch | grep "*" | sed "s/\* //"')
reflog_message= out('git reflog -1')
merged_branch_name=out('echo '+reflog_message+' | cut -d" " -f 4 | sed "s/://"')
print("[INFO] Preparing to merge "+ merged_branch_name  +" into  "+ branch_name)

if branch_name == "develop":
    out("git checkout --ours version.txt")
